[package]
name = "crowdfunding"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"

[dev-dependencies]
snforge_std = "0.45.0"
assert_macros = "2.11.4"


[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
